#!/usr/bin/env ruby
# ~/scripts/open_subl
require 'cgi'
require 'uri'
query = CGI.parse(URI.parse(ARGV.first).query)
url = query['url'].first
file = URI.parse(url).path
line = query['line'].first
column = query['column'].first
str = [file]
str << line unless line.nil?
str << column unless column.nil?
`subl #{str.join(':')}`
